insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("사과", "food", 2000, "맛있는 사과는 산지애", 50, "아주 달달해요!")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("바나나", "food", 3000, "델몬트", 15, "영양가가 높은 버내너~")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("휴지", "dailySupplies", 24900, "잘풀리는집", 23, "순수PURE 천연펄프 25m30롤 x3팩/휴지/화장지")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("섬유유연제", "dailySupplies", 18900, "피죤", 50, "피죤 섬유유연제 3100ml 6개골라담기")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("칫솔", "dailySupplies", 3900, "좋은칫솔", 80, "좋은칫솔 초극세모 10입")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("Gram 노트북", "homeAppliances", 749000, "LG", 12, "울트라PC 그램 14Z960 6세대 i5탑재")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("믹서기", "homeAppliances", 38900, "테팔", 22, "테팔 블렌더(믹서기) 블렌드포스 플러스 BL4258(블랙)")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("스킨", "beauty", 30000, "설화수", 45, "자음생수 125ml")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("백팩", "fashion", 18000, "샤오미", 7, "샤오미 비지니스 백팩")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("반팔", "fashion", 4500, "슈프림", 68, "반팔 브이넥")